<?php

namespace Net\Bazzline\MediaLibrary\Model\Database\Media\map;

use \RelationMap;
use \TableMap;


/**
 * This class defines the structure of the 'net_bazzline_media_library_media_common' table.
 *
 *
 * This class was autogenerated by Propel 1.6.9 on:
 *
 * Sun Aug 18 01:40:02 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.Media.map
 */
class MediaTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'Media.map.MediaTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('net_bazzline_media_library_media_common');
        $this->setPhpName('Media');
        $this->setClassname('Net\\Bazzline\\MediaLibrary\\Model\\Database\\Media\\Media');
        $this->setPackage('Media');
        $this->setUseIdGenerator(false);
        // columns
        $this->addPrimaryKey('id', 'Id', 'CHAR', true, 36, null);
        $this->addForeignKey('distributor_id', 'DistributorId', 'CHAR', 'net_bazzline_media_library_media_distributor', 'id', true, 36, null);
        $this->addForeignKey('edition_id', 'EditionId', 'CHAR', 'net_bazzline_media_library_media_edition', 'id', true, 36, null);
        $this->addForeignKey('type_id', 'TypeId', 'CHAR', 'net_bazzline_media_library_media_type', 'id', true, 36, null);
        $this->addForeignKey('user_id', 'UserId', 'CHAR', 'net_bazzline_media_library_user_users', 'id', true, 36, null);
        $this->addColumn('age_limit', 'AgeLimit', 'TINYINT', true, 2, 0);
        $this->addColumn('create_date', 'CreateDate', 'TIMESTAMP', true, null, 'CURRENT_TIMESTAMP');
        $this->addColumn('release_date', 'ReleaseDate', 'TIMESTAMP', true, null, '0000-00-00 00:00:00');
        $this->addColumn('name', 'Name', 'VARCHAR', true, 120, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Distributor', 'Net\\Bazzline\\MediaLibrary\\Model\\Database\\Media\\Distributor', RelationMap::MANY_TO_ONE, array('distributor_id' => 'id', ), null, null);
        $this->addRelation('Edition', 'Net\\Bazzline\\MediaLibrary\\Model\\Database\\Media\\Edition', RelationMap::MANY_TO_ONE, array('edition_id' => 'id', ), null, null);
        $this->addRelation('Type', 'Net\\Bazzline\\MediaLibrary\\Model\\Database\\Media\\Type', RelationMap::MANY_TO_ONE, array('type_id' => 'id', ), null, null);
        $this->addRelation('User', 'Net\\Bazzline\\MediaLibrary\\Model\\Database\\User\\User', RelationMap::MANY_TO_ONE, array('user_id' => 'id', ), null, null);
        $this->addRelation('Audio', 'Net\\Bazzline\\MediaLibrary\\Model\\Database\\Media\\Audio', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'Audios');
        $this->addRelation('Book', 'Net\\Bazzline\\MediaLibrary\\Model\\Database\\Media\\Book', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'Books');
        $this->addRelation('Video', 'Net\\Bazzline\\MediaLibrary\\Model\\Database\\Media\\Video', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'Videos');
        $this->addRelation('Game', 'Net\\Bazzline\\MediaLibrary\\Model\\Database\\Media\\Game', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'Games');
        $this->addRelation('Comment', 'Net\\Bazzline\\MediaLibrary\\Model\\Database\\Media\\Comment', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'Comments');
        $this->addRelation('MediaToArtist', 'Net\\Bazzline\\MediaLibrary\\Model\\Database\\Media\\MediaToArtist', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'MediaToArtists');
        $this->addRelation('MediaToGenre', 'Net\\Bazzline\\MediaLibrary\\Model\\Database\\Media\\MediaToGenre', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'MediaToGenres');
        $this->addRelation('MediaToLanguage', 'Net\\Bazzline\\MediaLibrary\\Model\\Database\\Media\\MediaToLanguage', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'MediaToLanguages');
    } // buildRelations()

} // MediaTableMap
