<?php

namespace Net\Bazzline\MediaLibrary\Model\Database\User;

use Net\Bazzline\MediaLibrary\Model\Database\User\om\BaseUserPeer;


/**
 * Skeleton subclass for performing query and update operations on the 'net_bazzline_media_library_user_users' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.9 on:
 *
 * Sun Aug 18 00:35:24 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.net-bazzline-media-library
 */
class UserPeer extends BaseUserPeer
{
}
