<?php

namespace Database\Media;

use Database\Media\om\BaseGameQuery;


/**
 * Skeleton subclass for performing query and update operations on the 'net_bazzline_media_library_media_game' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Wed Oct  1 21:22:56 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.Media
 */
class GameQuery extends BaseGameQuery
{
}
