<?php

namespace Database\Media;

use Database\Media\om\BaseArtist;


/**
 * Skeleton subclass for representing a row from the 'net_bazzline_media_library_media_artists' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Wed Oct  1 21:22:55 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.Media
 */
class Artist extends BaseArtist
{
}
