<?php

namespace Database\Media\Audio\om;

use \Criteria;
use \Exception;
use \ModelCriteria;
use \ModelJoin;
use \PDO;
use \Propel;
use \PropelCollection;
use \PropelException;
use \PropelObjectCollection;
use \PropelPDO;
use Database\Media\Audio;
use Database\Media\Audio\Track;
use Database\Media\Audio\TrackPeer;
use Database\Media\Audio\TrackQuery;

/**
 * Base class that represents a query for the 'net_bazzline_media_library_media_audio_track' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Fri Mar 28 23:55:59 2014
 *
 * @method TrackQuery orderById($order = Criteria::ASC) Order by the id column
 * @method TrackQuery orderByName($order = Criteria::ASC) Order by the name column
 * @method TrackQuery orderByAudioId($order = Criteria::ASC) Order by the audio_id column
 * @method TrackQuery orderByNumberOfPlay($order = Criteria::ASC) Order by the number_of_play column
 * @method TrackQuery orderByNumberOfDisc($order = Criteria::ASC) Order by the number_of_disc column
 * @method TrackQuery orderByDuration($order = Criteria::ASC) Order by the duration column
 *
 * @method TrackQuery groupById() Group by the id column
 * @method TrackQuery groupByName() Group by the name column
 * @method TrackQuery groupByAudioId() Group by the audio_id column
 * @method TrackQuery groupByNumberOfPlay() Group by the number_of_play column
 * @method TrackQuery groupByNumberOfDisc() Group by the number_of_disc column
 * @method TrackQuery groupByDuration() Group by the duration column
 *
 * @method TrackQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method TrackQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method TrackQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method TrackQuery leftJoinAudio($relationAlias = null) Adds a LEFT JOIN clause to the query using the Audio relation
 * @method TrackQuery rightJoinAudio($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Audio relation
 * @method TrackQuery innerJoinAudio($relationAlias = null) Adds a INNER JOIN clause to the query using the Audio relation
 *
 * @method Track findOne(PropelPDO $con = null) Return the first Track matching the query
 * @method Track findOneOrCreate(PropelPDO $con = null) Return the first Track matching the query, or a new Track object populated from the query conditions when no match is found
 *
 * @method Track findOneByName(string $name) Return the first Track filtered by the name column
 * @method Track findOneByAudioId(string $audio_id) Return the first Track filtered by the audio_id column
 * @method Track findOneByNumberOfPlay(int $number_of_play) Return the first Track filtered by the number_of_play column
 * @method Track findOneByNumberOfDisc(int $number_of_disc) Return the first Track filtered by the number_of_disc column
 * @method Track findOneByDuration(int $duration) Return the first Track filtered by the duration column
 *
 * @method array findById(string $id) Return Track objects filtered by the id column
 * @method array findByName(string $name) Return Track objects filtered by the name column
 * @method array findByAudioId(string $audio_id) Return Track objects filtered by the audio_id column
 * @method array findByNumberOfPlay(int $number_of_play) Return Track objects filtered by the number_of_play column
 * @method array findByNumberOfDisc(int $number_of_disc) Return Track objects filtered by the number_of_disc column
 * @method array findByDuration(int $duration) Return Track objects filtered by the duration column
 *
 * @package    propel.generator.Media.om
 */
abstract class BaseTrackQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseTrackQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = null, $modelName = null, $modelAlias = null)
    {
        if (null === $dbName) {
            $dbName = 'netBazzlineMediaLibrary';
        }
        if (null === $modelName) {
            $modelName = 'Database\\Media\\Audio\\Track';
        }
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new TrackQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param   TrackQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return TrackQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof TrackQuery) {
            return $criteria;
        }
        $query = new TrackQuery(null, null, $modelAlias);

        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Track|Track[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = TrackPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is already in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(TrackPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Alias of findPk to use instance pooling
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 Track A model object, or null if the key is not found
     * @throws PropelException
     */
     public function findOneById($key, $con = null)
     {
        return $this->findPk($key, $con);
     }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 Track A model object, or null if the key is not found
     * @throws PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT id, name, audio_id, number_of_play, number_of_disc, duration FROM net_bazzline_media_library_media_audio_track WHERE id = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_STR);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Track();
            $obj->hydrate($row);
            TrackPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Track|Track[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Track[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return TrackQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(TrackPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return TrackQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(TrackPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById('fooValue');   // WHERE id = 'fooValue'
     * $query->filterById('%fooValue%'); // WHERE id LIKE '%fooValue%'
     * </code>
     *
     * @param     string $id The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TrackQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($id)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $id)) {
                $id = str_replace('*', '%', $id);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TrackPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the name column
     *
     * Example usage:
     * <code>
     * $query->filterByName('fooValue');   // WHERE name = 'fooValue'
     * $query->filterByName('%fooValue%'); // WHERE name LIKE '%fooValue%'
     * </code>
     *
     * @param     string $name The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TrackQuery The current query, for fluid interface
     */
    public function filterByName($name = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($name)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $name)) {
                $name = str_replace('*', '%', $name);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TrackPeer::NAME, $name, $comparison);
    }

    /**
     * Filter the query on the audio_id column
     *
     * Example usage:
     * <code>
     * $query->filterByAudioId('fooValue');   // WHERE audio_id = 'fooValue'
     * $query->filterByAudioId('%fooValue%'); // WHERE audio_id LIKE '%fooValue%'
     * </code>
     *
     * @param     string $audioId The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TrackQuery The current query, for fluid interface
     */
    public function filterByAudioId($audioId = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($audioId)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $audioId)) {
                $audioId = str_replace('*', '%', $audioId);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TrackPeer::AUDIO_ID, $audioId, $comparison);
    }

    /**
     * Filter the query on the number_of_play column
     *
     * Example usage:
     * <code>
     * $query->filterByNumberOfPlay(1234); // WHERE number_of_play = 1234
     * $query->filterByNumberOfPlay(array(12, 34)); // WHERE number_of_play IN (12, 34)
     * $query->filterByNumberOfPlay(array('min' => 12)); // WHERE number_of_play >= 12
     * $query->filterByNumberOfPlay(array('max' => 12)); // WHERE number_of_play <= 12
     * </code>
     *
     * @param     mixed $numberOfPlay The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TrackQuery The current query, for fluid interface
     */
    public function filterByNumberOfPlay($numberOfPlay = null, $comparison = null)
    {
        if (is_array($numberOfPlay)) {
            $useMinMax = false;
            if (isset($numberOfPlay['min'])) {
                $this->addUsingAlias(TrackPeer::NUMBER_OF_PLAY, $numberOfPlay['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($numberOfPlay['max'])) {
                $this->addUsingAlias(TrackPeer::NUMBER_OF_PLAY, $numberOfPlay['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TrackPeer::NUMBER_OF_PLAY, $numberOfPlay, $comparison);
    }

    /**
     * Filter the query on the number_of_disc column
     *
     * Example usage:
     * <code>
     * $query->filterByNumberOfDisc(1234); // WHERE number_of_disc = 1234
     * $query->filterByNumberOfDisc(array(12, 34)); // WHERE number_of_disc IN (12, 34)
     * $query->filterByNumberOfDisc(array('min' => 12)); // WHERE number_of_disc >= 12
     * $query->filterByNumberOfDisc(array('max' => 12)); // WHERE number_of_disc <= 12
     * </code>
     *
     * @param     mixed $numberOfDisc The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TrackQuery The current query, for fluid interface
     */
    public function filterByNumberOfDisc($numberOfDisc = null, $comparison = null)
    {
        if (is_array($numberOfDisc)) {
            $useMinMax = false;
            if (isset($numberOfDisc['min'])) {
                $this->addUsingAlias(TrackPeer::NUMBER_OF_DISC, $numberOfDisc['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($numberOfDisc['max'])) {
                $this->addUsingAlias(TrackPeer::NUMBER_OF_DISC, $numberOfDisc['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TrackPeer::NUMBER_OF_DISC, $numberOfDisc, $comparison);
    }

    /**
     * Filter the query on the duration column
     *
     * Example usage:
     * <code>
     * $query->filterByDuration(1234); // WHERE duration = 1234
     * $query->filterByDuration(array(12, 34)); // WHERE duration IN (12, 34)
     * $query->filterByDuration(array('min' => 12)); // WHERE duration >= 12
     * $query->filterByDuration(array('max' => 12)); // WHERE duration <= 12
     * </code>
     *
     * @param     mixed $duration The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TrackQuery The current query, for fluid interface
     */
    public function filterByDuration($duration = null, $comparison = null)
    {
        if (is_array($duration)) {
            $useMinMax = false;
            if (isset($duration['min'])) {
                $this->addUsingAlias(TrackPeer::DURATION, $duration['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($duration['max'])) {
                $this->addUsingAlias(TrackPeer::DURATION, $duration['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TrackPeer::DURATION, $duration, $comparison);
    }

    /**
     * Filter the query by a related Audio object
     *
     * @param   Audio|PropelObjectCollection $audio The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 TrackQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByAudio($audio, $comparison = null)
    {
        if ($audio instanceof Audio) {
            return $this
                ->addUsingAlias(TrackPeer::AUDIO_ID, $audio->getId(), $comparison);
        } elseif ($audio instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(TrackPeer::AUDIO_ID, $audio->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByAudio() only accepts arguments of type Audio or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Audio relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return TrackQuery The current query, for fluid interface
     */
    public function joinAudio($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Audio');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Audio');
        }

        return $this;
    }

    /**
     * Use the Audio relation Audio object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   \Database\Media\AudioQuery A secondary query class using the current class as primary query
     */
    public function useAudioQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinAudio($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Audio', '\Database\Media\AudioQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   Track $track Object to remove from the list of results
     *
     * @return TrackQuery The current query, for fluid interface
     */
    public function prune($track = null)
    {
        if ($track) {
            $this->addUsingAlias(TrackPeer::ID, $track->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
