<?php

namespace Database\Media;

use Database\Media\om\BaseGenrePeer;


/**
 * Skeleton subclass for performing query and update operations on the 'net_bazzline_media_library_media_genre' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Thu Mar 27 21:22:22 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.Media
 */
class GenrePeer extends BaseGenrePeer
{
}
