<?php

namespace Database\Media\om;

use \Criteria;
use \Exception;
use \ModelCriteria;
use \ModelJoin;
use \PDO;
use \Propel;
use \PropelCollection;
use \PropelException;
use \PropelObjectCollection;
use \PropelPDO;
use Database\Media\Book;
use Database\Media\BookPeer;
use Database\Media\BookQuery;
use Database\Media\Media;

/**
 * Base class that represents a query for the 'net_bazzline_media_library_media_book' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Wed Oct  1 21:22:56 2014
 *
 * @method BookQuery orderById($order = Criteria::ASC) Order by the id column
 * @method BookQuery orderByMediaId($order = Criteria::ASC) Order by the media_id column
 * @method BookQuery orderByNumberOfPages($order = Criteria::ASC) Order by the number_of_pages column
 * @method BookQuery orderByIsbn10($order = Criteria::ASC) Order by the isbn_10 column
 * @method BookQuery orderByIsbn13($order = Criteria::ASC) Order by the isbn_13 column
 *
 * @method BookQuery groupById() Group by the id column
 * @method BookQuery groupByMediaId() Group by the media_id column
 * @method BookQuery groupByNumberOfPages() Group by the number_of_pages column
 * @method BookQuery groupByIsbn10() Group by the isbn_10 column
 * @method BookQuery groupByIsbn13() Group by the isbn_13 column
 *
 * @method BookQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method BookQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method BookQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method BookQuery leftJoinMedia($relationAlias = null) Adds a LEFT JOIN clause to the query using the Media relation
 * @method BookQuery rightJoinMedia($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Media relation
 * @method BookQuery innerJoinMedia($relationAlias = null) Adds a INNER JOIN clause to the query using the Media relation
 *
 * @method Book findOne(PropelPDO $con = null) Return the first Book matching the query
 * @method Book findOneOrCreate(PropelPDO $con = null) Return the first Book matching the query, or a new Book object populated from the query conditions when no match is found
 *
 * @method Book findOneByMediaId(string $media_id) Return the first Book filtered by the media_id column
 * @method Book findOneByNumberOfPages(int $number_of_pages) Return the first Book filtered by the number_of_pages column
 * @method Book findOneByIsbn10(string $isbn_10) Return the first Book filtered by the isbn_10 column
 * @method Book findOneByIsbn13(string $isbn_13) Return the first Book filtered by the isbn_13 column
 *
 * @method array findById(string $id) Return Book objects filtered by the id column
 * @method array findByMediaId(string $media_id) Return Book objects filtered by the media_id column
 * @method array findByNumberOfPages(int $number_of_pages) Return Book objects filtered by the number_of_pages column
 * @method array findByIsbn10(string $isbn_10) Return Book objects filtered by the isbn_10 column
 * @method array findByIsbn13(string $isbn_13) Return Book objects filtered by the isbn_13 column
 *
 * @package    propel.generator.Media.om
 */
abstract class BaseBookQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseBookQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = null, $modelName = null, $modelAlias = null)
    {
        if (null === $dbName) {
            $dbName = 'netBazzlineMediaLibrary';
        }
        if (null === $modelName) {
            $modelName = 'Database\\Media\\Book';
        }
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new BookQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param   BookQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return BookQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof BookQuery) {
            return $criteria;
        }
        $query = new BookQuery(null, null, $modelAlias);

        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Book|Book[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = BookPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is already in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(BookPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Alias of findPk to use instance pooling
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 Book A model object, or null if the key is not found
     * @throws PropelException
     */
     public function findOneById($key, $con = null)
     {
        return $this->findPk($key, $con);
     }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 Book A model object, or null if the key is not found
     * @throws PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT id, media_id, number_of_pages, isbn_10, isbn_13 FROM net_bazzline_media_library_media_book WHERE id = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_STR);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Book();
            $obj->hydrate($row);
            BookPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Book|Book[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Book[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return BookQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(BookPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return BookQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(BookPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById('fooValue');   // WHERE id = 'fooValue'
     * $query->filterById('%fooValue%'); // WHERE id LIKE '%fooValue%'
     * </code>
     *
     * @param     string $id The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return BookQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($id)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $id)) {
                $id = str_replace('*', '%', $id);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(BookPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the media_id column
     *
     * Example usage:
     * <code>
     * $query->filterByMediaId('fooValue');   // WHERE media_id = 'fooValue'
     * $query->filterByMediaId('%fooValue%'); // WHERE media_id LIKE '%fooValue%'
     * </code>
     *
     * @param     string $mediaId The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return BookQuery The current query, for fluid interface
     */
    public function filterByMediaId($mediaId = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($mediaId)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $mediaId)) {
                $mediaId = str_replace('*', '%', $mediaId);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(BookPeer::MEDIA_ID, $mediaId, $comparison);
    }

    /**
     * Filter the query on the number_of_pages column
     *
     * Example usage:
     * <code>
     * $query->filterByNumberOfPages(1234); // WHERE number_of_pages = 1234
     * $query->filterByNumberOfPages(array(12, 34)); // WHERE number_of_pages IN (12, 34)
     * $query->filterByNumberOfPages(array('min' => 12)); // WHERE number_of_pages >= 12
     * $query->filterByNumberOfPages(array('max' => 12)); // WHERE number_of_pages <= 12
     * </code>
     *
     * @param     mixed $numberOfPages The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return BookQuery The current query, for fluid interface
     */
    public function filterByNumberOfPages($numberOfPages = null, $comparison = null)
    {
        if (is_array($numberOfPages)) {
            $useMinMax = false;
            if (isset($numberOfPages['min'])) {
                $this->addUsingAlias(BookPeer::NUMBER_OF_PAGES, $numberOfPages['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($numberOfPages['max'])) {
                $this->addUsingAlias(BookPeer::NUMBER_OF_PAGES, $numberOfPages['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(BookPeer::NUMBER_OF_PAGES, $numberOfPages, $comparison);
    }

    /**
     * Filter the query on the isbn_10 column
     *
     * Example usage:
     * <code>
     * $query->filterByIsbn10('fooValue');   // WHERE isbn_10 = 'fooValue'
     * $query->filterByIsbn10('%fooValue%'); // WHERE isbn_10 LIKE '%fooValue%'
     * </code>
     *
     * @param     string $isbn10 The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return BookQuery The current query, for fluid interface
     */
    public function filterByIsbn10($isbn10 = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($isbn10)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $isbn10)) {
                $isbn10 = str_replace('*', '%', $isbn10);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(BookPeer::ISBN_10, $isbn10, $comparison);
    }

    /**
     * Filter the query on the isbn_13 column
     *
     * Example usage:
     * <code>
     * $query->filterByIsbn13('fooValue');   // WHERE isbn_13 = 'fooValue'
     * $query->filterByIsbn13('%fooValue%'); // WHERE isbn_13 LIKE '%fooValue%'
     * </code>
     *
     * @param     string $isbn13 The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return BookQuery The current query, for fluid interface
     */
    public function filterByIsbn13($isbn13 = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($isbn13)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $isbn13)) {
                $isbn13 = str_replace('*', '%', $isbn13);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(BookPeer::ISBN_13, $isbn13, $comparison);
    }

    /**
     * Filter the query by a related Media object
     *
     * @param   Media|PropelObjectCollection $media The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 BookQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByMedia($media, $comparison = null)
    {
        if ($media instanceof Media) {
            return $this
                ->addUsingAlias(BookPeer::MEDIA_ID, $media->getId(), $comparison);
        } elseif ($media instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(BookPeer::MEDIA_ID, $media->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByMedia() only accepts arguments of type Media or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Media relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return BookQuery The current query, for fluid interface
     */
    public function joinMedia($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Media');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Media');
        }

        return $this;
    }

    /**
     * Use the Media relation Media object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   \Database\Media\MediaQuery A secondary query class using the current class as primary query
     */
    public function useMediaQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinMedia($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Media', '\Database\Media\MediaQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   Book $book Object to remove from the list of results
     *
     * @return BookQuery The current query, for fluid interface
     */
    public function prune($book = null)
    {
        if ($book) {
            $this->addUsingAlias(BookPeer::ID, $book->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
