<?php

namespace Net\Bazzline\MediaLibrary\Model\Database\Media;

use Net\Bazzline\MediaLibrary\Model\Database\Media\om\BaseGamePlattformPeer;


/**
 * Skeleton subclass for performing query and update operations on the 'net_bazzline_media_library_media_game_plattform' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.9 on:
 *
 * Sun Aug 18 01:40:02 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.Media
 */
class GamePlattformPeer extends BaseGamePlattformPeer
{
}
